-- PlanetsLib:update({
--     {
--         type = "planet",
--         name = "aquilo",
--         orbit = {
--             parent = {
--                 type = "space-location",
--                 name = "star"
--             },
--             distance = 75,
-- 			orientation = 0.35
--         }
--     }
-- })
